name: Ubuntu

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v3
        
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Tests
        run: make tests
